### ISSUE TITLE
Be more explicit about ecdsa being only optional

### ISSUE THREAD

**Issue by jackjack-jj** [jackjack-jj/pywallet#21]

**Comment by maikelmclauflin** [comment]
it does not seem like this is the case. default setup seems to require and fail when ecdsa is not available and it also seems that i have ecdsa, but that it is not in my path and i am given no indication of where it might be

```
Successfully installed ecdsa-0.17.0
macport@local electrum % ecdsa
zsh: command not found: ecdsa
```

**Comment by jackjack-jj** [comment]
Could you post the error showing ecdsa is required to run pywallet?
For example this command should work
`python pywallet.py --info --importprivkey 1`
