### ISSUE TITLE
New error "AttributeError: 'Bdict' object has no attribute 'has_key'"

### ISSUE THREAD

**Issue by gildash2** [jackjack-jj/pywallet#28]

**Comment by gildash2** [comment]
Also get the following error when running:

python pywallet.py --dumpwallet --wallet=wallet.dat

Traceback (most recent call last):
  File "pywallet.py", line 2316, in parse_wallet
    item_callback(type, d)
  File "pywallet.py", line 2654, in item_callback
    if not json_db.has_key('settings'):
AttributeError: 'Bdict' object has no attribute 'has_key'
ERROR parsing wallet.dat, type b'setting'
key data: REDACTED
key data in hex: REDACTED
value data in hex: REDACTED

**Comment by erm3nda** [comment]
In python3, has_key(key) is replaced by __contains__(key)

https://stackoverflow.com/a/56356127/2480481
