### ISSUE TITLE
same 2013 walet issue

### ISSUE THREAD

**Issue by xxxoloxxx** [jackjack-jj/pywallet#29]
Traceback (most recent call last):
  File "pywallet.py", line 3749, in <module>
    recoveredKeys=recov(device, passes, size, 10240, options.recov_outputdir)
  File "pywallet.py", line 1801, in recov
    if len(ckeys_not_decrypted)==0:
TypeError: object of type 'filter' has no len()

**Comment by xxxoloxxx** [comment]
4000.00 Go read
4000.00 Go read
4000.00 Go read
4000.00 Go read
4000.00 Go read
4000.00 Go read
4000.00 Go read
|
Read 4000.0 Go in 1201.0 minutes
|
Found 146 possible wallets
Found 3418 possible encrypted keys
Found 10258 possible unencrypted keys
|
|
Possible wallet #146
    with passphrase #1
    with passphrase #2
|
Private keys not decrypted: 3418
Trying all the remaining possibilities (998056) might take up to 2772 minutes.
Do you want to test them? (y/n): y
|
The wallet is encrypted and the passphrase is correct
|
Importing:
Importing key    1/10258
pywallet.py:2827: UserWarning: Hexadecimal private keys must be 64 or 66 characters long (specified one is 0 characters long)
pywallet.py:2830: UserWarning: Padding with zeroes, uncompressed
Traceback (most recent call last):
  File "pywallet.py", line 3786, in <module>
    importprivkey(db, sec, "recovered: %s"%sec, None, False)
  File "pywallet.py", line 2898, in importprivkey
    k = keyinfo(sec, network, verbose)
  File "pywallet.py", line 2856, in keyinfo
    (pkey, compressed) = parse_private_key(sec, force_compressed)
  File "pywallet.py", line 2834, in parse_private_key
    warnings.warn(e)
TypeError: expected string or buffer

**Comment by danielverdugo** [comment]
Any updates?

**Comment by jackjack-jj** [comment]
99316a1 should fix that
