### ISSUE TITLE
ERROR parsing wallet.dat, type setting

### ISSUE THREAD

**Issue by M4xSec** [jackjack-jj/pywallet#31]
my command= python pywallet.py --dumpwallet --dumpwithbalance --wallet=/root/Desktop/TXT/pywallet/wallet.dat --passphrase=<pwd>
------------
ERROR showing-
  File "pywallet.py", line 1471, in deserialize_CAddress
    return d['ip']+":"+str(d['port'])
  File "pywallet.py", line 109, in __getitem__
    return super(Bdict, self).__getitem__(bytes_to_str(k))
KeyError: u'ip'
ERROR parsing wallet.dat, type setting

**Comment by jdestefx** [comment]
Same error here.

**Comment by jackjack-jj** [comment]
Should be fixed now
