### ISSUE TITLE
"balance": "error code: 1015

### ISSUE THREAD

**Issue by tarnok** [jackjack-jj/pywallet#33]
Any way we can fix this? I have a wallet with over 100 entries and checking them all sucks,

**Comment by wschoot** [comment]
This is actually CloudFlare in front of blockchain preventing you from "hammering" their site. I found the following API better:
https://api.blockcypher.com/v1/btc/main/addrs/$pubkey/balance

**Comment by jackjack-jj** [comment]
The PR has been merged
